function v3(x,y,z){return{x,y,z};}
function add(a,b){return v3(a.x+b.x,a.y+b.y,a.z+b.z);}
function sub(a,b){return v3(a.x-b.x,a.y-b.y,a.z-b.z);}
function scale(a,s){return v3(a.x*s,a.y*s,a.z*s);}
function dot(a,b){return a.x*b.x+a.y*b.y+a.z*b.z;}
function cross(a,b){return v3(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x);}
function length(a){return Math.sqrt(dot(a,a));}
function normalize(a){const l=length(a);return l===0?v3(0,0,0):scale(a,1/l);}
function negateV(a){return v3(-a.x,-a.y,-a.z);}
function lerpV(a,b,t){return add(a,scale(sub(b,a),t));}
function makeVertex(pos,normal){return{pos,normal};}
function interpolateVertex(a,b,t){return makeVertex(lerpV(a.pos,b.pos,t),normalize(lerpV(a.normal,b.normal,t)));}
function flipVertex(v){return makeVertex(v.pos,negateV(v.normal));}
const EPSILON=1e-5;
function planeFromPoints(a,b,c){const n=normalize(cross(sub(b,a),sub(c,a)));return{normal:n,w:dot(n,a)};}
function flipPlane(p){return{normal:negateV(p.normal),w:-p.w};}
const COPLANAR=0,FRONT=1,BACK=2,SPANNING=3;
function splitPolygon(plane,polygon,coplanarFront,coplanarBack,front,back){let polygonType=0;const types=[];for(const v of polygon.vertices){const t=dot(plane.normal,v.pos)-plane.w;const type=t<-EPSILON?BACK:t>EPSILON?FRONT:COPLANAR;polygonType|=type;types.push(type);}switch(polygonType){case COPLANAR:(dot(plane.normal,polygon.plane.normal)>0?coplanarFront:coplanarBack).push(polygon);break;case FRONT:front.push(polygon);break;case BACK:back.push(polygon);break;case SPANNING:{const f=[],b=[];for(let i=0;i<polygon.vertices.length;i++){const j=(i+1)%polygon.vertices.length;const ti=types[i],tj=types[j],vi=polygon.vertices[i],vj=polygon.vertices[j];if(ti!==BACK)f.push(vi);if(ti!==FRONT)b.push(ti!==BACK?makeVertex(vi.pos,vi.normal):vi);if((ti|tj)===SPANNING){const t=(plane.w-dot(plane.normal,vi.pos))/dot(plane.normal,sub(vj.pos,vi.pos));const v=interpolateVertex(vi,vj,t);f.push(v);b.push(v);}}if(f.length>=3)front.push(makePolygon(f));if(b.length>=3)back.push(makePolygon(b));break;}}}
function makePolygon(vertices){return{vertices,plane:planeFromPoints(vertices[0].pos,vertices[1].pos,vertices[2].pos)};}
function flipPolygon(p){return{vertices:[...p.vertices].reverse().map(flipVertex),plane:flipPlane(p.plane)};}
function newNode(polygons){const node={plane:null,front:null,back:null,polygons:[]};if(polygons&&polygons.length)buildNode(node,polygons);return node;}
function invertNode(node){node.polygons=node.polygons.map(flipPolygon);if(node.plane)node.plane=flipPlane(node.plane);if(node.front)invertNode(node.front);if(node.back)invertNode(node.back);const t=node.front;node.front=node.back;node.back=t;}
function clipPolygonsAgainstNode(node,polygons){if(!node.plane)return polygons.slice();let front=[],back=[];for(const p of polygons)splitPolygon(node.plane,p,front,back,front,back);front=node.front?clipPolygonsAgainstNode(node.front,front):front;back=node.back?clipPolygonsAgainstNode(node.back,back):[];return front.concat(back);}
function clipToNode(node,other){node.polygons=clipPolygonsAgainstNode(other,node.polygons);if(node.front)clipToNode(node.front,other);if(node.back)clipToNode(node.back,other);}
function allPolygonsInNode(node){let p=node.polygons.slice();if(node.front)p=p.concat(allPolygonsInNode(node.front));if(node.back)p=p.concat(allPolygonsInNode(node.back));return p;}
function buildNode(node,polygons){if(!polygons.length)return;if(!node.plane)node.plane={...polygons[0].plane};const front=[],back=[];for(const p of polygons)splitPolygon(node.plane,p,node.polygons,node.polygons,front,back);if(front.length){if(!node.front)node.front=newNode();buildNode(node.front,front);}if(back.length){if(!node.back)node.back=newNode();buildNode(node.back,back);}}
function csgUnion(A,B){const a=newNode(A),b=newNode(B);clipToNode(a,b);clipToNode(b,a);invertNode(b);clipToNode(b,a);invertNode(b);buildNode(a,allPolygonsInNode(b));return allPolygonsInNode(a);}
function csgSubtract(A,B){const a=newNode(A),b=newNode(B);invertNode(a);clipToNode(a,b);clipToNode(b,a);invertNode(b);clipToNode(b,a);invertNode(b);buildNode(a,allPolygonsInNode(b));invertNode(a);return allPolygonsInNode(a);}
function csgIntersect(A,B){const a=newNode(A),b=newNode(B);invertNode(a);clipToNode(b,a);invertNode(b);clipToNode(a,b);clipToNode(b,a);buildNode(a,allPolygonsInNode(b));invertNode(a);return allPolygonsInNode(a);}
function cube(center=v3(0,0,0),size=v3(1,1,1)){const c=center,s=scale(size,.5),defs=[[[0,4,6,2],[-1,0,0]],[[1,3,7,5],[1,0,0]],[[0,1,5,4],[0,-1,0]],[[2,6,7,3],[0,1,0]],[[0,2,3,1],[0,0,-1]],[[4,5,7,6],[0,0,1]]],corners=[];for(let i=0;i<8;i++)corners.push(v3(c.x+(i&1?s.x:-s.x),c.y+(i&2?s.y:-s.y),c.z+(i&4?s.z:-s.z)));return defs.map(([idx,n])=>makePolygon(idx.map(i=>makeVertex(corners[i],v3(...n)))));}
function sphere(center=v3(0,0,0),radius=1,slices=16,stacks=8){const polys=[];function va(t,p){const d=v3(Math.cos(t)*Math.sin(p),Math.cos(p),Math.sin(t)*Math.sin(p));return makeVertex(add(center,scale(d,radius)),d);}for(let i=0;i<slices;i++)for(let j=0;j<stacks;j++){const verts=[],t0=i/slices*Math.PI*2,t1=(i+1)/slices*Math.PI*2,p0=j/stacks*Math.PI,p1=(j+1)/stacks*Math.PI;verts.push(va(t0,p0));if(j>0)verts.push(va(t1,p0));verts.push(va(t1,p1));if(j<stacks-1)verts.push(va(t0,p1));if(verts.length>=3)polys.push(makePolygon(verts));}return polys;}
function cylinder(start=v3(0,-1,0),end=v3(0,1,0),radius=1,slices=16){const axis=normalize(sub(end,start)),notAxis=Math.abs(axis.y)<.9?v3(0,1,0):v3(1,0,0),px=normalize(cross(notAxis,axis)),py=cross(axis,px);function pt(t,a){const out=add(scale(px,Math.cos(a)*radius),scale(py,Math.sin(a)*radius)),base=lerpV(start,end,t);return{pos:add(base,out),normal:out};}const polys=[];for(let i=0;i<slices;i++){const a0=i/slices*Math.PI*2,a1=(i+1)/slices*Math.PI*2,p0=pt(0,a0),p1=pt(0,a1),p2=pt(1,a1),p3=pt(1,a0);polys.push(makePolygon([makeVertex(p0.pos,normalize(p0.normal)),makeVertex(p1.pos,normalize(p1.normal)),makeVertex(p2.pos,normalize(p2.normal)),makeVertex(p3.pos,normalize(p3.normal))]));polys.push(makePolygon([makeVertex(start,negateV(axis)),makeVertex(pt(0,a1).pos,negateV(axis)),makeVertex(pt(0,a0).pos,negateV(axis))]));polys.push(makePolygon([makeVertex(end,axis),makeVertex(pt(1,a0).pos,axis),makeVertex(pt(1,a1).pos,axis)]));}return polys;}
function translatePolygons(polygons,offset){return polygons.map(p=>({vertices:p.vertices.map(v=>makeVertex(add(v.pos,offset),v.normal)),plane:{normal:p.plane.normal,w:p.plane.w+dot(p.plane.normal,offset)}}));}
function boundingBox(polygons){if(!polygons.length)return null;let min={...polygons[0].vertices[0].pos},max={...min};for(const p of polygons)for(const v of p.vertices){min=v3(Math.min(min.x,v.pos.x),Math.min(min.y,v.pos.y),Math.min(min.z,v.pos.z));max=v3(Math.max(max.x,v.pos.x),Math.max(max.y,v.pos.y),Math.max(max.z,v.pos.z));}return{min,max};}
function isDegenerateResult(polygons){if(!polygons.length)return true;const b=boundingBox(polygons),s=sub(b.max,b.min);return s.x<EPSILON&&s.y<EPSILON&&s.z<EPSILON;}
function parseSTL(text){const polys=[],lines=text.split('\n').map(l=>l.trim());let verts=[],n=v3(0,0,1);for(const line of lines){if(line.startsWith('facet normal')){const p=line.split(/\s+/).slice(2).map(Number);n=v3(p[0],p[1],p[2]);verts=[];}else if(line.startsWith('vertex')){const p=line.split(/\s+/).slice(1).map(Number);verts.push(makeVertex(v3(p[0],p[1],p[2]),n));}else if(line.startsWith('endfacet')){if(verts.length===3)polys.push(makePolygon(verts));verts=[];}}return polys;}
function toSTL(polygons,name='solid'){const lines=[`solid ${name}`];for(const p of polygons)for(let i=1;i<p.vertices.length-1;i++){const tri=[p.vertices[0],p.vertices[i],p.vertices[i+1]],n=p.plane.normal;lines.push(` facet normal ${n.x} ${n.y} ${n.z}`,'  outer loop');for(const v of tri)lines.push(`   vertex ${v.pos.x} ${v.pos.y} ${v.pos.z}`);lines.push('  endloop',' endfacet');}lines.push(`endsolid ${name}`);return lines.join('\n');}
window.CSGEngine={v3,add,sub,scale,dot,cross,length,normalize,cube,sphere,cylinder,csgUnion,csgSubtract,csgIntersect,toSTL,translatePolygons,boundingBox,isDegenerateResult,parseSTL};
