const fileInput=document.getElementById('open-package'),tree=document.getElementById('project-tree'),validateBtn=document.getElementById('validate-project'),statusBox=document.getElementById('job-status'),drop=document.getElementById('workspace-drop'),exportPart=document.getElementById('export-part'),exportAll=document.getElementById('export-all'),prepareAll=document.getElementById('prepare-all');
let currentFile=null,parts=[],selected=-1;
const log=m=>statusBox.textContent=m;
const printable=n=>/\.(stl|3mf)$/i.test(n);
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function render(){tree.innerHTML='<strong>Project</strong><br>'+parts.map((p,i)=>`<div class="part ${i===selected?'active':''}" data-i="${i}">├─ ${p.name}</div>`).join('');drop.innerHTML=parts.length?`<strong>${parts.length} printable part${parts.length===1?'':'s'} ready</strong><br><br>${parts.map(p=>p.name).join('<br>')}`:'<strong>No printable STL/3MF parts found.</strong>';tree.querySelectorAll('.part').forEach(el=>el.onclick=()=>{selected=Number(el.dataset.i);render();exportPart.disabled=false;log(`Selected ${parts[selected].name}.\nPrinter: FlashForge Adventurer 5M / 0.4 mm\nMaterial: PLA\nReady for slicer handoff.`)})}
fileInput.addEventListener('change',()=>{currentFile=fileInput.files?.[0]||null;parts=[];selected=-1;exportPart.disabled=exportAll.disabled=prepareAll.disabled=true;if(!currentFile){tree.textContent='No package loaded.';validateBtn.disabled=true;return}tree.textContent=`Project\n└─ ${currentFile.name}\n   └─ size: ${(currentFile.size/1024).toFixed(1)} KB`;drop.innerHTML=`<strong>${currentFile.name}</strong><br><br>Package selected. Validate to expand printable parts.`;validateBtn.disabled=false;log(`Opened ${currentFile.name}.\nAwaiting validation.`)});
validateBtn.addEventListener('click',async()=>{if(!currentFile)return;validateBtn.disabled=true;try{const ext=currentFile.name.split('.').pop().toLowerCase();if(ext==='zip'){if(typeof JSZip==='undefined')throw new Error('ZIP engine did not load. Refresh the page and retry.');const zip=await JSZip.loadAsync(currentFile);for(const [name,entry] of Object.entries(zip.files)){if(!entry.dir&&printable(name)){parts.push({name:name.split('/').pop(),blob:await entry.async('blob')})}}}else if(printable(currentFile.name)){parts=[{name:currentFile.name,blob:currentFile}]}else throw new Error('Unsupported package type.');if(!parts.length)throw new Error('No STL or 3MF files were found in this package.');selected=0;render();exportPart.disabled=false;exportAll.disabled=false;prepareAll.disabled=false;log(`Validation complete.\nExpanded ${parts.length} printable part(s).\nFlashForge Adventurer 5M / 0.4 mm selected.\nPLA selected.\nChoose a part or export the complete assembly for slicing.`)}catch(e){log('Validation failed: '+e.message)}finally{validateBtn.disabled=false}});
prepareAll.onclick=()=>{selected=-1;render();log(`Complete assembly prepared: ${parts.length} printable part(s).\nProfile: Adventurer 5M / PLA / 0.20 mm / 20% infill.\nUse “Download all printable parts”, then import them into Flash Studio Desktop for machine-code slicing.`)};
exportPart.onclick=()=>{if(selected<0||!parts[selected])return;download(parts[selected].blob,parts[selected].name);log(`Exported ${parts[selected].name}.\nImport it into Flash Studio Desktop and select Adventurer 5M / 0.4 mm / PLA.`)};
exportAll.onclick=async()=>{if(!parts.length)return;if(typeof JSZip==='undefined'){log('ZIP engine unavailable. Refresh and retry.');return}const z=new JSZip();parts.forEach(p=>z.file(p.name,p.blob));const b=await z.generateAsync({type:'blob'});download(b,'UNG_DRACO_AD5M_PRINT_PARTS.zip');log(`Exported ${parts.length} printable parts as UNG_DRACO_AD5M_PRINT_PARTS.zip.\nNext: open Flash Studio Desktop → Adventurer 5M / 0.4 mm → PLA → import parts → slice → send to printer.`)};
