const E=CSGEngine,H=HistoryStack,viewport=document.getElementById('viewport'),scene=new THREE.Scene();scene.background=new THREE.Color(0x0f172a);const camera=new THREE.PerspectiveCamera(50,1,.1,1000),renderer=new THREE.WebGLRenderer({antialias:true});viewport.insertBefore(renderer.domElement,viewport.firstChild);const controls=new THREE.OrbitControls(camera,renderer.domElement);scene.add(new THREE.AmbientLight(0xffffff,.65));const dl=new THREE.DirectionalLight(0xffffff,.9);dl.position.set(10,15,10);scene.add(dl);scene.add(new THREE.GridHelper(20,20,0x475569,0x1e293b));scene.add(new THREE.AxesHelper(5));let objects=[],selectedIds=[],nextId=1,wire=false,currentSceneId=null,history=H.createHistory([]);const colors=[0x3b82f6,0x22c55e,0xf59e0b,0xef4444,0xa855f7];
function setView(v='iso'){const d=12,p={iso:[d,d,d],front:[0,0,d],top:[0,d,.001],side:[d,0,0]}[v];camera.position.set(...p);camera.lookAt(0,0,0);controls.update()}setView();
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)})();
function meshFrom(polys,i){const pos=[],nor=[];for(const p of polys)for(let k=1;k<p.vertices.length-1;k++)for(const v of [p.vertices[0],p.vertices[k],p.vertices[k+1]]){pos.push(v.pos.x,v.pos.y,v.pos.z);nor.push(v.normal.x,v.normal.y,v.normal.z)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(nor,3));return new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:colors[i%colors.length],side:THREE.DoubleSide,wireframe:wire}))}
function snap(){return objects.map(o=>({id:o.id,name:o.name,polygons:o.polygons,position:o.position,visible:o.visible}))}function record(){history=H.pushState(history,snap());histBtns()}function status(t){document.getElementById('status').textContent=t}
function addObj(name,polygons,position,doHistory=true){const mesh=meshFrom(polygons,objects.length);scene.add(mesh);const o={id:nextId++,name,polygons,position,mesh,visible:true};objects.push(o);refresh();if(doHistory)record();return o}
function rebuild(o){scene.remove(o.mesh);o.mesh=meshFrom(o.polygons,objects.indexOf(o));o.mesh.visible=o.visible;scene.add(o.mesh)}
function remove(ids,doHistory=true){ids.forEach(id=>{const o=objects.find(x=>x.id===id);if(o)scene.remove(o.mesh)});objects=objects.filter(o=>!ids.includes(o.id));selectedIds=selectedIds.filter(id=>!ids.includes(id));refresh();if(doHistory)record()}
function restore(s){objects.forEach(o=>scene.remove(o.mesh));objects=[];selectedIds=[];for(const x of s){const o=addObj(x.name,x.polygons,x.position,false);o.id=x.id;o.visible=x.visible!==false;o.mesh.visible=o.visible;nextId=Math.max(nextId,o.id+1)}refresh()}
function refresh(){const l=document.getElementById('object-list');l.innerHTML='';objects.forEach(o=>{const d=document.createElement('div');d.className='obj'+(selectedIds.includes(o.id)?' sel':'');d.innerHTML=`<span>${o.name}</span><span>${o.visible?'👁':'◌'}</span>`;d.onclick=e=>{if(e.target!==d.firstChild){o.visible=!o.visible;o.mesh.visible=o.visible;refresh();return}if(e.shiftKey){selectedIds.includes(o.id)?selectedIds=selectedIds.filter(id=>id!==o.id):selectedIds.push(o.id)}else selectedIds=[o.id];refresh()};l.appendChild(d)});document.querySelectorAll('[data-op]').forEach(b=>b.disabled=selectedIds.length!==2);const one=selectedIds.length===1?objects.find(o=>o.id===selectedIds[0]):null;['rename-input','pos-x','pos-y','pos-z','move-btn','duplicate-btn'].forEach(id=>document.getElementById(id).disabled=!one);document.getElementById('delete-btn').disabled=!selectedIds.length;if(one){rename.value=one.name;px.value=one.position.x;py.value=one.position.y;pz.value=one.position.z}else{rename.value='';px.value=py.value=pz.value=''}histBtns()}
function histBtns(){undo.disabled=!H.canUndo(history);redo.disabled=!H.canRedo(history)}
const rename=document.getElementById('rename-input'),px=document.getElementById('pos-x'),py=document.getElementById('pos-y'),pz=document.getElementById('pos-z'),undo=document.getElementById('undo-btn'),redo=document.getElementById('redo-btn');
primitiveType=document.getElementById('primitive-type');primitiveType.onchange=()=>{cubeDims.style.display=primitiveType.value==='cube'?'flex':'none';sphereDims.style.display=primitiveType.value==='sphere'?'flex':'none';cylinderDims.style.display=primitiveType.value==='cylinder'?'flex':'none'};const cubeDims=document.getElementById('cube-dims'),sphereDims=document.getElementById('sphere-dims'),cylinderDims=document.getElementById('cylinder-dims');
document.getElementById('add-btn').onclick=()=>{const t=primitiveType.value,off=objects.length*1.5,c=E.v3(off,0,0);let p,n;if(t==='cube'){const w=+document.getElementById('cube-w').value||2,h=+document.getElementById('cube-h').value||2,d=+document.getElementById('cube-d').value||2;p=E.cube(c,E.v3(w,h,d));n=`Cube ${objects.length+1}`}else if(t==='sphere'){const r=+document.getElementById('sphere-r').value||1.2;p=E.sphere(c,r);n=`Sphere ${objects.length+1}`}else{const r=+document.getElementById('cyl-r').value||1,h=+document.getElementById('cyl-h').value||3;p=E.cylinder(E.v3(off,-h/2,0),E.v3(off,h/2,0),r,16);n=`Cylinder ${objects.length+1}`}addObj(n,p,c);status('Added '+n)};
rename.onchange=()=>{const o=objects.find(x=>x.id===selectedIds[0]);if(o){o.name=rename.value||o.name;refresh();record()}};document.getElementById('move-btn').onclick=()=>{const o=objects.find(x=>x.id===selectedIds[0]),t=E.v3(+px.value||0,+py.value||0,+pz.value||0),d=E.sub(t,o.position);o.polygons=E.translatePolygons(o.polygons,d);o.position=t;rebuild(o);record();status('Moved '+o.name)};document.getElementById('duplicate-btn').onclick=()=>{const o=objects.find(x=>x.id===selectedIds[0]),d=E.v3(1,0,1);addObj(o.name+' copy',E.translatePolygons(o.polygons,d),E.add(o.position,d));status('Duplicated '+o.name)};document.getElementById('delete-btn').onclick=()=>{remove([...selectedIds]);status('Deleted')};
document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{const [a,bid]=selectedIds.map(id=>objects.find(o=>o.id===id)),op=b.dataset.op;loading.style.display='flex';setTimeout(()=>{let p=op==='union'?E.csgUnion(a.polygons,bid.polygons):op==='subtract'?E.csgSubtract(a.polygons,bid.polygons):E.csgIntersect(a.polygons,bid.polygons);loading.style.display='none';if(E.isDegenerateResult(p)){status('Boolean result was empty/degenerate.');return}remove([a.id,bid.id],false);addObj(`${op}(${a.name}, ${bid.name})`,p,E.v3(0,0,0),false);record();status(op+' complete')},20)});const loading=document.getElementById('loading');
undo.onclick=()=>{history=H.undo(history);restore(history.present);histBtns();status('Undid last action')};redo.onclick=()=>{history=H.redo(history);restore(history.present);histBtns();status('Redid action')};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('wireframe-btn').onclick=()=>{wire=!wire;objects.forEach(o=>o.mesh.material.wireframe=wire);status('Wireframe '+(wire?'on':'off'))};
document.getElementById('export-btn').onclick=()=>{let p=[];objects.filter(o=>o.visible).forEach(o=>p=p.concat(o.polygons));if(!p.length){status('Nothing to export');return}const blob=new Blob([E.toSTL(p,'ung_cad_export')],{type:'model/stl'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ung_cad_export.stl';a.click();status('Exported STL')};document.getElementById('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;loading.style.display='flex';try{if(/\.zip$/i.test(f.name)){const z=await JSZip.loadAsync(f),names=Object.keys(z.files).filter(n=>/\.stl$/i.test(n)&&!z.files[n].dir);if(!names.length)throw new Error('ZIP contains no STL geometry');let n=0;for(const name of names){const raw=await z.files[name].async('arraybuffer');let p=E.parseSTL(raw);if(!p.length){const txt=new TextDecoder().decode(raw);p=E.parseSTL(txt)}if(p.length){addObj(name.split('/').pop().replace(/\.stl$/i,''),p,E.v3((n%3)*2,0,Math.floor(n/3)*2),false);n++}}if(!n)throw new Error('Could not parse STL geometry in ZIP');record();status('Imported '+n+' STL parts from '+f.name)}else if(/\.stl$/i.test(f.name)){const raw=await f.arrayBuffer();let p=E.parseSTL(raw);if(!p.length)p=E.parseSTL(new TextDecoder().decode(raw));if(!p.length)throw new Error('Could not parse STL');addObj(f.name.replace(/\.stl$/i,''),p,E.v3(0,0,0));status('Imported '+f.name)}else if(/\.3mf$/i.test(f.name)){throw new Error('3MF selected; geometry parser is not installed yet')}else throw new Error('Unsupported file type')}catch(err){status('Import failed: '+err.message)}finally{loading.style.display='none';resize()}};
async function refreshSaved(){try{const list=await fetch('/api/scenes').then(r=>r.json()),el=document.getElementById('saved-list');el.innerHTML='';list.forEach(s=>{const d=document.createElement('div');d.className='muted';d.style.padding='6px 0';d.style.cursor='pointer';d.textContent='↳ '+s.name;d.onclick=()=>loadScene(s.id);el.appendChild(d)})}catch{status('Save backend unavailable')}}async function loadScene(id){const r=await fetch('/api/scenes/'+id);if(!r.ok)return status('Load failed');const s=await r.json();currentSceneId=id;document.getElementById('scene-name').value=s.name;restore(s.data.objects||[]);history=H.createHistory(s.data.objects||[]);histBtns();status("Loaded '"+s.name+"'")}
document.getElementById('save-btn').onclick=async()=>{const name=document.getElementById('scene-name').value||'Untitled scene',body=JSON.stringify({name,data:{objects:snap()}}),opt={method:currentSceneId?'PUT':'POST',headers:{'Content-Type':'application/json'},body},url=currentSceneId?'/api/scenes/'+currentSceneId:'/api/scenes';const r=await fetch(url,opt);if(!r.ok)return status('Save failed');if(!currentSceneId)currentSceneId=(await r.json()).id;status("Saved '"+name+"'");refreshSaved()};refresh();refreshSaved();status('UNG-CAD ready');
